/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as GenerateIndexRouteImport } from './routes/generate/index'
import { Route as FeedsIndexRouteImport } from './routes/feeds/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as SettingsWoocommerceRouteImport } from './routes/settings/woocommerce'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiTemplatesIndexRouteImport } from './routes/api/templates/index'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index'
import { Route as ApiMediaIndexRouteImport } from './routes/api/media/index'
import { Route as ApiWooSyncRouteImport } from './routes/api/woo/sync'
import { Route as ApiWooConnectionsRouteImport } from './routes/api/woo/connections'
import { Route as ApiUserSettingsRouteImport } from './routes/api/user/settings'
import { Route as ApiTemplatesRulesPreviewRouteImport } from './routes/api/templates/rules-preview'
import { Route as ApiTemplatesRulesRouteImport } from './routes/api/templates/rules'
import { Route as ApiTemplatesPreviewRouteImport } from './routes/api/templates/preview'
import { Route as ApiTemplatesAssignmentsRouteImport } from './routes/api/templates/assignments'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiMediaProxyRouteImport } from './routes/api/media/proxy'
import { Route as ApiAuthRegistrationStatusRouteImport } from './routes/api/auth/registration-status'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateIndexRoute = GenerateIndexRouteImport.update({
  id: '/generate/',
  path: '/generate/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWoocommerceRoute = SettingsWoocommerceRouteImport.update({
  id: '/settings/woocommerce',
  path: '/settings/woocommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIndexRoute = ApiTemplatesIndexRouteImport.update({
  id: '/api/templates/',
  path: '/api/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIndexRoute = ApiMediaIndexRouteImport.update({
  id: '/api/media/',
  path: '/api/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWooSyncRoute = ApiWooSyncRouteImport.update({
  id: '/api/woo/sync',
  path: '/api/woo/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWooConnectionsRoute = ApiWooConnectionsRouteImport.update({
  id: '/api/woo/connections',
  path: '/api/woo/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSettingsRoute = ApiUserSettingsRouteImport.update({
  id: '/api/user/settings',
  path: '/api/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRulesPreviewRoute =
  ApiTemplatesRulesPreviewRouteImport.update({
    id: '/api/templates/rules-preview',
    path: '/api/templates/rules-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTemplatesRulesRoute = ApiTemplatesRulesRouteImport.update({
  id: '/api/templates/rules',
  path: '/api/templates/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesPreviewRoute = ApiTemplatesPreviewRouteImport.update({
  id: '/api/templates/preview',
  path: '/api/templates/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesAssignmentsRoute = ApiTemplatesAssignmentsRouteImport.update({
  id: '/api/templates/assignments',
  path: '/api/templates/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaProxyRoute = ApiMediaProxyRouteImport.update({
  id: '/api/media/proxy',
  path: '/api/media/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegistrationStatusRoute =
  ApiAuthRegistrationStatusRouteImport.update({
    id: '/api/auth/registration-status',
    path: '/api/auth/registration-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/settings/woocommerce': typeof SettingsWoocommerceRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/feeds': typeof FeedsIndexRoute
  '/generate': typeof GenerateIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/registration-status': typeof ApiAuthRegistrationStatusRoute
  '/api/media/proxy': typeof ApiMediaProxyRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/templates/assignments': typeof ApiTemplatesAssignmentsRoute
  '/api/templates/preview': typeof ApiTemplatesPreviewRoute
  '/api/templates/rules': typeof ApiTemplatesRulesRoute
  '/api/templates/rules-preview': typeof ApiTemplatesRulesPreviewRoute
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/api/woo/connections': typeof ApiWooConnectionsRoute
  '/api/woo/sync': typeof ApiWooSyncRoute
  '/api/media': typeof ApiMediaIndexRoute
  '/api/products': typeof ApiProductsIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/settings/woocommerce': typeof SettingsWoocommerceRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/feeds': typeof FeedsIndexRoute
  '/generate': typeof GenerateIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/registration-status': typeof ApiAuthRegistrationStatusRoute
  '/api/media/proxy': typeof ApiMediaProxyRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/templates/assignments': typeof ApiTemplatesAssignmentsRoute
  '/api/templates/preview': typeof ApiTemplatesPreviewRoute
  '/api/templates/rules': typeof ApiTemplatesRulesRoute
  '/api/templates/rules-preview': typeof ApiTemplatesRulesPreviewRoute
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/api/woo/connections': typeof ApiWooConnectionsRoute
  '/api/woo/sync': typeof ApiWooSyncRoute
  '/api/media': typeof ApiMediaIndexRoute
  '/api/products': typeof ApiProductsIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/settings/woocommerce': typeof SettingsWoocommerceRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/feeds/': typeof FeedsIndexRoute
  '/generate/': typeof GenerateIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/registration-status': typeof ApiAuthRegistrationStatusRoute
  '/api/media/proxy': typeof ApiMediaProxyRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/templates/assignments': typeof ApiTemplatesAssignmentsRoute
  '/api/templates/preview': typeof ApiTemplatesPreviewRoute
  '/api/templates/rules': typeof ApiTemplatesRulesRoute
  '/api/templates/rules-preview': typeof ApiTemplatesRulesPreviewRoute
  '/api/user/settings': typeof ApiUserSettingsRoute
  '/api/woo/connections': typeof ApiWooConnectionsRoute
  '/api/woo/sync': typeof ApiWooSyncRoute
  '/api/media/': typeof ApiMediaIndexRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/settings/woocommerce'
    | '/templates/$templateId'
    | '/feeds'
    | '/generate'
    | '/products'
    | '/settings'
    | '/templates'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/registration-status'
    | '/api/media/proxy'
    | '/api/media/upload'
    | '/api/templates/assignments'
    | '/api/templates/preview'
    | '/api/templates/rules'
    | '/api/templates/rules-preview'
    | '/api/user/settings'
    | '/api/woo/connections'
    | '/api/woo/sync'
    | '/api/media'
    | '/api/products'
    | '/api/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/settings/woocommerce'
    | '/templates/$templateId'
    | '/feeds'
    | '/generate'
    | '/products'
    | '/settings'
    | '/templates'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/registration-status'
    | '/api/media/proxy'
    | '/api/media/upload'
    | '/api/templates/assignments'
    | '/api/templates/preview'
    | '/api/templates/rules'
    | '/api/templates/rules-preview'
    | '/api/user/settings'
    | '/api/woo/connections'
    | '/api/woo/sync'
    | '/api/media'
    | '/api/products'
    | '/api/templates'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/settings/woocommerce'
    | '/templates/$templateId'
    | '/feeds/'
    | '/generate/'
    | '/products/'
    | '/settings/'
    | '/templates/'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/registration-status'
    | '/api/media/proxy'
    | '/api/media/upload'
    | '/api/templates/assignments'
    | '/api/templates/preview'
    | '/api/templates/rules'
    | '/api/templates/rules-preview'
    | '/api/user/settings'
    | '/api/woo/connections'
    | '/api/woo/sync'
    | '/api/media/'
    | '/api/products/'
    | '/api/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  SettingsWoocommerceRoute: typeof SettingsWoocommerceRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  FeedsIndexRoute: typeof FeedsIndexRoute
  GenerateIndexRoute: typeof GenerateIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthRegistrationStatusRoute: typeof ApiAuthRegistrationStatusRoute
  ApiMediaProxyRoute: typeof ApiMediaProxyRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiTemplatesAssignmentsRoute: typeof ApiTemplatesAssignmentsRoute
  ApiTemplatesPreviewRoute: typeof ApiTemplatesPreviewRoute
  ApiTemplatesRulesRoute: typeof ApiTemplatesRulesRoute
  ApiTemplatesRulesPreviewRoute: typeof ApiTemplatesRulesPreviewRoute
  ApiUserSettingsRoute: typeof ApiUserSettingsRoute
  ApiWooConnectionsRoute: typeof ApiWooConnectionsRoute
  ApiWooSyncRoute: typeof ApiWooSyncRoute
  ApiMediaIndexRoute: typeof ApiMediaIndexRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
  ApiTemplatesIndexRoute: typeof ApiTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/': {
      id: '/generate/'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/woocommerce': {
      id: '/settings/woocommerce'
      path: '/settings/woocommerce'
      fullPath: '/settings/woocommerce'
      preLoaderRoute: typeof SettingsWoocommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/': {
      id: '/api/templates/'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/': {
      id: '/api/media/'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/woo/sync': {
      id: '/api/woo/sync'
      path: '/api/woo/sync'
      fullPath: '/api/woo/sync'
      preLoaderRoute: typeof ApiWooSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/woo/connections': {
      id: '/api/woo/connections'
      path: '/api/woo/connections'
      fullPath: '/api/woo/connections'
      preLoaderRoute: typeof ApiWooConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/settings': {
      id: '/api/user/settings'
      path: '/api/user/settings'
      fullPath: '/api/user/settings'
      preLoaderRoute: typeof ApiUserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/rules-preview': {
      id: '/api/templates/rules-preview'
      path: '/api/templates/rules-preview'
      fullPath: '/api/templates/rules-preview'
      preLoaderRoute: typeof ApiTemplatesRulesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/rules': {
      id: '/api/templates/rules'
      path: '/api/templates/rules'
      fullPath: '/api/templates/rules'
      preLoaderRoute: typeof ApiTemplatesRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/preview': {
      id: '/api/templates/preview'
      path: '/api/templates/preview'
      fullPath: '/api/templates/preview'
      preLoaderRoute: typeof ApiTemplatesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/assignments': {
      id: '/api/templates/assignments'
      path: '/api/templates/assignments'
      fullPath: '/api/templates/assignments'
      preLoaderRoute: typeof ApiTemplatesAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/proxy': {
      id: '/api/media/proxy'
      path: '/api/media/proxy'
      fullPath: '/api/media/proxy'
      preLoaderRoute: typeof ApiMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/registration-status': {
      id: '/api/auth/registration-status'
      path: '/api/auth/registration-status'
      fullPath: '/api/auth/registration-status'
      preLoaderRoute: typeof ApiAuthRegistrationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  SettingsWoocommerceRoute: SettingsWoocommerceRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  FeedsIndexRoute: FeedsIndexRoute,
  GenerateIndexRoute: GenerateIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthRegistrationStatusRoute: ApiAuthRegistrationStatusRoute,
  ApiMediaProxyRoute: ApiMediaProxyRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiTemplatesAssignmentsRoute: ApiTemplatesAssignmentsRoute,
  ApiTemplatesPreviewRoute: ApiTemplatesPreviewRoute,
  ApiTemplatesRulesRoute: ApiTemplatesRulesRoute,
  ApiTemplatesRulesPreviewRoute: ApiTemplatesRulesPreviewRoute,
  ApiUserSettingsRoute: ApiUserSettingsRoute,
  ApiWooConnectionsRoute: ApiWooConnectionsRoute,
  ApiWooSyncRoute: ApiWooSyncRoute,
  ApiMediaIndexRoute: ApiMediaIndexRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
  ApiTemplatesIndexRoute: ApiTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
